// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB70fG4srCFaumAfxYf2ZjxtxvYsTg6jbc',
    appId: '1:258403543773:web:286c7986d9292297690934',
    messagingSenderId: '258403543773',
    projectId: 'flutterfirebase-b9562',
    authDomain: 'flutterfirebase-b9562.firebaseapp.com',
    storageBucket: 'flutterfirebase-b9562.appspot.com',
    measurementId: 'G-1BJ60CY03R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl6_0K3KuC-INMD0Z9StrOT834tOBwtxk',
    appId: '1:258403543773:android:c7277f4d32df4820690934',
    messagingSenderId: '258403543773',
    projectId: 'flutterfirebase-b9562',
    storageBucket: 'flutterfirebase-b9562.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnKsDMjFBYrCkKy20I4lvE_gdcO47rEAw',
    appId: '1:258403543773:ios:74b98b36b1a9bb68690934',
    messagingSenderId: '258403543773',
    projectId: 'flutterfirebase-b9562',
    storageBucket: 'flutterfirebase-b9562.appspot.com',
    iosBundleId: 'com.example.auth',
  );
}
